Question 1. By Borna Maherani
ID = 401243079

<h1>Initializing n,m and Linearly indipendent vectors</h1>
درین بخش اول مقادیر ان و ام را گرفته و به تعداد ام بار هر بردار را در یک خط ورودی گرفته و بعد از ورودی گرفتن بردار جدید به مقایشه رنک ها می پردازیم.
از آنجایی که بردار ها مستقل خطی میباشند اگر رنک ماتریس بردار ها با رنک ماتریس بردار های جدید یکسان باشد به این معنی میباشد که بردار جدید ما مستقل خطی نسبت به بردار های توصیف کننده فضا نمیباشد و پایه های غیر متغامد و غیر یکه ما همان بردار های اولیه میباشد. در غیر این صورت پایه های ما بردار های قبلی به علاوه بردار جدید میباشد. 

In [5]:
import numpy as np
#Dimension of the space : R^n
n = int(input())
#number of vectors that discribe the space
m = int(input())
#array of vectors
X = np.empty((0,n), int)
#New Vector
Xnew = np.empty((0,n) , int)

"""
geting the vectors (every input should be in a line and splited by 'space')
example: n=4 , m=3 
1 3 4 0
0 0 4 9
10 4 1 1
"""

for row in range(0,m):
    line = input().split()
    line = list(map(int, line))
    X = np.append(X, np.array([line]), axis=0)
line = input().split()
line = list(map(int, line))
Xnew = np.append(Xnew, np.array([line]), axis=0)

#Rank of vectors(without Xnew)
X_Rank = np.linalg.matrix_rank(X)

temp = np.vstack([X,Xnew])
#Rank of vectors + Xnew
X_newRank = np.linalg.matrix_rank(temp)

#if the newrank = rank + 1
if(X_newRank != X_Rank):
    #new bases are X + Xnew
    X = temp
    gram(X,m+1,n)
#newrank = rank
else:
    gram(X,m,n)


ValueError: invalid literal for int() with base 10: ''

<h1>Gram-Schmidt Algorithm</h1>
پس از مشخص شدن مجموعه بردار های پایه آنهارا با استفاده از الگوریتم گرام اشمیت اول متعامد نسبت به یکدیگر و سپس آنها را یکه میکنیم.


In [46]:
import numpy as np
#dot operation for two vectors
def nDot(v1,v2,n):
    #n is dimension of vectros
    result = 0
    for i in range (n):
        result += v1[i] * v2[i]
    return result

# proj of v1 on v2
def proj(v1,v2,n):
    return (nDot(v1,v2,n)/nDot(v2,v2,n)) * v2

#main  algorithm
def gram(X,m,n):
    #Bases that nor orthogonal nor unit vector
    Base = np.empty((0,n), float)
    for i in range (0,m):
        lenBase = len(Base)
        tempBase = X[i]
        #making the vectors 
        for j in range (lenBase):
            tempBase -= proj(X[i],Base[j],n)
        #making the orthogonal vectors also unit vectors
        tempBase = tempBase/np.linalg.norm(tempBase)
        #adding the new base into bases array 
        Base = np.append(Base, np.array([tempBase]), axis=0)
    return Base


[[0. 1. 0.]
 [1. 0. 0.]]


<h1>TestCases</h1>

In [51]:
A = np.array([
    [1.,0.,2.,4.],
    [3.,4.,0.,0.],
    [2.,0.,3.,0.]
])
print(gram(A,3,4))
A = np.array([
    [1.,0.,0.,0.],
    [0.,4.,0.,0.],
    [1.,0.,3.,0.]
])
print(gram(A,3,4))

[[ 0.21821789  0.          0.43643578  0.87287156]
 [ 0.57639042  0.80694658 -0.05763904 -0.11527808]
 [ 0.35157263 -0.26367947  0.76518749 -0.4704869 ]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
